version: "3.8"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    develop:
      watch:
        - action: rebuild
          files:
            - ./**/*.go
            - ./go.mod
            - ./go.sum
          path: .
    ports:
      - "2345:2345"
  nginx:
    image: nginx:alpine
